config/routes.rb
Rails.application.routes.draw do
  resources :cards
  devise_for :users
  root to: "cards#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
	STATUS = {BACKLOG: 'Backlog', INPROGRESS: 'InProgress',DONE: 'Done',QAVERIFIED: 'QAVerified'}
	TICKET_TYPES = {NORMAL: 'Normal',MAJOR: 'Major',CRITICAL: 'Critical',SHOWSTOPPER: 'Show-stopper'}
	belongs_to :user
	belongs_to :assignee, class_name: 'User', foreign_key: :assignee_id

	after_update :send_email

	def send_email
		#emailer logic
		#CardsMailer.notify_update(id).deliver_later
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :cards
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  # GET /cards
  # GET /cards.json
  def index
    if params['query'].present?
      @query = params['query']
      cards = Card.where("title LIKE '#{params['query']}'")
    else
      cards = Card.all
    end
    @cards = cards.present? ? cards.select('id, title, status').order('updated_at desc').group_by(&:status).sort.to_h : []
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:title, :description, :status, :user_id, :assignee_id, :due_date, :ticket_type)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def users
	  options = {}
	  users = User.all
	  users.each {|user| options = options.merge({user.email => user.id})}
	  options
	end

	def status
		options = {}
		Card::STATUS.each {|st| options = options.merge({st[1] => st[1]})}
		options
	end

	def ticket_types
		options = {}
		Card::TICKET_TYPES.each {|st| options = options.merge({st[1] => st[1]})}
		options
	end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_form.html.haml
.container
  .row
    .col-md-8.offset-md-2
      .card.mt-3
        .card-header      
          Card
        .card-body
          = form_with(model: card, local: true) do |form|
            - if card.errors.any?
              #error_explanation
                %h2
                  = pluralize(card.errors.count, "error")
                  prohibited this card from being saved:
                %ul
                  - card.errors.full_messages.each do |message|
                    %li= message
            .form-group
              %label Title
              = form.text_area :title, id: :card_title, class: 'form-control', required: true
            .form-group
              %label Description
              = form.text_area :description, id: :card_description, class: 'form-control', required: true
            .form-group
              %label Status
              = form.select :status, options_for_select(status, form.object.status), {}, {class: 'form-control',prompt: 'Please select', required: true, id: :card_status}
            = form.hidden_field :user_id, :value => current_user.id
            .form-group
              %label Assignee
              = form.select :assignee_id,options_for_select(users, form.object.assignee_id), {},{prompt: 'Please select', required: true, id: :card_assignee_id, class: 'form-control'}
            .form-group
              %label Due Date
              = form.date_select :due_date, id: :card_due_date, class: 'form-control'
            .form-group
              %label Ticket Type
              = form.select :ticket_type, options_for_select(ticket_types, form.object.ticket_type), {},{prompt: "Please select", :required => true, id: :card_ticket_type, class: 'form-control'}
            .actions
              = submit_tag 'Create', class: 'btn btn-primary float-right'
              = link_to 'Back', root_path, class: 'btn btn-default float-left'

app/views/cards/edit.html.erb
<%= render 'form', card: @card %>

app/views/cards/index.html.haml
:css
  .sortable_list {
    border: 1px solid #eee;
    width: 142px;
    min-height: 20px;
    list-style-type: none;
    margin: 0;
    padding: 5px 0 0 0;
    float: left;
    margin-right: 10px;
  }

  .sortable_list li {
    margin: 0 5px 5px 5px;
    padding: 5px;
    font-size: 1.2em;
    width: 120px;
  }

.container
  .row.mt-3
    = form_tag cards_path, method: :get do
      .input-group.mb-3
        = text_field_tag 'query', @query || '',placeholder: 'Search by title', class: 'form-control'
        .input-group-append
          = submit_tag 'Search',class: 'btn btn-outline-secondary'
          = link_to 'Clear', cards_path,class: 'btn btn-outline-secondary'
  .row.mt-3
    - @cards.each do |cards|
      .col-md-3.col-lg-3.col-sm-3
        .card
          .card-header
            = cards[0]
          .card-body
            %ul#sortable.sortable_list.connectedSortable{id: cards[0]}
              - cards[1].each do |card|
                %a{href: "cards/#{card.id}", id: card.id}
                  %li.ui-state-default
                    = card.title


:javascript
  $(function() {
    $( ".sortable_list" ).sortable({
      connectWith: ".connectedSortable",
      receive: function(event, ui) {
        var new_status = this.id.split('_')[1];
        var item_id = ui.item[0].id;
        var params = {"card": {"status": new_status}, "id": item_id};
        $.ajax({
        type: 'PUT',
        url: '/cards/'+ item_id,
        data: params,
        dataType: 'JSON'
        }).done(function (data) {
          alert('Sucess');
        }).fail(function (data) {
          alert('Fail');
        });
      }         
    }).disableSelection();
  });

app/views/cards/new.html.erb
<%= render 'form', card: @card %>

app/views/cards/show.html.haml
%p#notice= notice

.container
  .row
    .col-md-10.offset-md-1
      .card.mt-3
        .card-header      
          Card Details
        .card-body
          %table.table.table-condensed.table-striped
            %thead
              %tr
                %th Title
                %th Description
                %th Creator
                %th Assignee
                %th Status
                %th Ticket Type
                %th Due Date
            %tbody
              %tr
                %td= @card.title
                %td= @card.description
                %td= @card.user.email
                %td= @card.assignee.email
                %td= @card.status
                %td= @card.ticket_type
                %td= @card.due_date
          .row
            = link_to 'Edit', edit_card_path(@card), class: 'btn btn-primary'
            = link_to 'Delete',card_path(@card), method: :delete, class: 'btn btn-danger'
            = link_to 'Back', root_path, class: 'btn btn-default'

app/views/layouts/_header.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light.justify-content-between
  %a.navbar-brand{:href => root_path} Agile Board  
  - if user_signed_in?
    .float-right
      = link_to 'New Card', new_card_path, class: 'btn btn-outline-success'
      = link_to 'Logout', destroy_user_session_path, method: :delete, class: 'btn btn-outline-success'

app/views/layouts/application.html.haml
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title AgileBoard
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    %link{:href => "//code.jquery.com/ui/1.11.0/themes/smoothness/jquery-ui.css", :rel => "stylesheet"}/
    = javascript_include_tag 'application'
    = javascript_include_tag "https://code.jquery.com/jquery-1.12.4.js"
    = javascript_include_tag "https://code.jquery.com/ui/1.12.1/jquery-ui.js"
  %body
    = render 'layouts/header'
    = yield